# -*- coding: utf-8 -*-
"""Healthcare Data Understanding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZiA9FcMhuLQCyx6s2oYG9ICPKIsUDRaQ
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("healthcare_dataset.csv")

from google.colab import files

uploaded = files.upload()

df.head()

print(df.tail())
print(df.info())

print(df.isnull().sum())

df = df.drop_duplicates()

df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], dayfirst=True)

df = df.sort_values("Admission_Date")

print(df.head(10))

print("Highest Billing Amount:", df["Billing_Amount"].max())
print("Lowest Billing Amount:", df["Billing_Amount"].min())
print("Average Billing Amount:", df["Billing_Amount"].mean())
print("Average Age:", df["Age"].mean())

df["Daily Billing Change"] = df["Billing_Amount"].diff()

print(df[["Admission_Date", "Billing_Amount", "Daily Billing Change"]])

plt.figure(figsize=(10,5))
plt.plot(df["Date"], df["Close"])
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.title("AAPL Stock Price Analysis")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

