# -*- coding: utf-8 -*-
"""Healthcare Data Understanding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QGULnqpltEf0r5aLtr18eVgb0-Ba6HPc
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn  as sns

df=pd.read_csv("/content/healthcare_dataset (1).csv")
display(df.head())

df['Medical Condition'].isnull()

print(df['Medical Condition'].value_counts())

df['Standardized_Medical_Condition'] = df['Medical Condition'].str.replace('ICD-10-', '')
print(df[['Medical Condition', 'Standardized_Medical_Condition']].head())

df['Admission_Date'] = pd.to_datetime(df['Date of Admission'], errors='coerce')
df['Discharge_Date'] = pd.to_datetime(df['Discharge Date'], errors='coerce')

df['Hospital_Stay_Days'] = (df['Discharge_Date'] - df['Admission_Date']).dt.days
display(df[['Admission_Date', 'Discharge_Date', 'Hospital_Stay_Days']].head())

print("Summary Statistics for Billing Amount:")
display(df['Billing Amount'].describe())
print("\nSummary Statistics for Hospital Stay Days:")
display(df['Hospital_Stay_Days'].describe())

plt.figure(figsize=(10, 6))
sns.histplot(df['Hospital_Stay_Days'], kde=True, bins=30)
plt.title('Distribution of Hospital Stay Days')
plt.xlabel('Hospital Stay Days')
plt.ylabel('Frequency')
plt.grid
plt.show()

df['Hospital_Stay_Days']=(df['Discharge_Date']-df['Admission_Date']).dt.days
print(df['Billing Amount'].describe())
print(df['Hospital_Stay_Days'].describe())