# -*- coding: utf-8 -*-
"""Shopify Stock Visualization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XpN6Tbs5vQztkwZqE76i02j969yui6RK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("shopify_stock.csv")

print("First 5 rows of the dataset:")
display(df.head())

plt.figure(figsize=(10, 5))

plt.plot(df["date"], df["close"])

plt.title("Shopify Closing Price Over Time")
plt.xlabel("Date")
plt.ylabel("Closing Price")
plt.grid()

plt.show()

df["MA20"] = df["close"].rolling(20).mean()
df["MA50"] = df["close"].rolling(50).mean()

plt.figure(figsize=(12, 6))

plt.plot(df["date"], df["close"], label="Closing Price")
plt.plot(df["date"], df["MA20"], label="20-Day Moving Average")
plt.plot(df["date"], df["MA50"], label="50-Day Moving Average")

plt.title("Shopify Closing Price with Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.grid()

plt.show()

df["daily_return"] = df["close"].pct_change() * 100

print(df[["date", "close", "daily_return"]].head())

plt.figure(figsize=(10, 5))

sns.histplot(df["daily_return"].dropna(), kde=True)

plt.title("Daily Return Distribution")
plt.xlabel("Daily Return (%)")
plt.ylabel("Frequency")

plt.show()

